import {
  SiAstro,
  SiBiome,
  SiC,
  SiCloudflare,
  SiCloudflarepages,
  SiCloudflareworkers,
  SiCss3,
  SiDocker,
  SiDrizzle,
  SiElectron,
  SiEslint,
  SiFastapi,
  SiFirebase,
  SiGit,
  SiGithub,
  SiGithubactions,
  SiHono,
  SiHtml5,
  SiInstagram,
  SiJavascript,
  SiJest,
  SiJupyter,
  SiMantine,
  SiMysql,
  SiNestjs,
  SiNextdotjs,
  SiNodedotjs,
  SiNumpy,
  SiPandas,
  SiPostgresql,
  SiPrettier,
  SiPrisma,
  SiPython,
  SiRaspberrypi,
  SiReact,
  SiRecoil,
  SiRemix,
  SiRubyonrails,
  SiSass,
  SiStorybook,
  SiStyledcomponents,
  SiSupabase,
  SiSvelte,
  SiTauri,
  SiThreedotjs,
  SiTrpc,
  SiTypescript,
  SiUnjs,
  SiVite,
  SiVitest,
  SiVuedotjs,
  SiX,
  SiRust,
  SiHugo,
  SiSwift,
  SiTensorflow,
  SiFlutter,
  SiTailwindcss,
  SiAwslambda,
  SiAmazonwebservices,
  SiPhp,
  SiKotlin,
} from '@icons-pack/react-simple-icons';
import { getKeys } from '@/utils';
import { TanstackIcon } from './customs';

export const ICON_MAP = {
  aws: { name: 'AWS', icon: SiAmazonwebservices },
  astro: { name: 'Astro', icon: SiAstro },
  biome: { name: 'Biome', icon: SiBiome },
  c: { name: 'C言語', icon: SiC },
  cloudflare: { name: 'Cloudflare', icon: SiCloudflare },
  'cloudflare-pages': { name: 'Cloudflare Pages', icon: SiCloudflarepages },
  'cloudflare-workers': { name: 'Cloudflare Workers', icon: SiCloudflareworkers },
  css: { name: 'CSS', icon: SiCss3 },
  docker: { name: 'Docker', icon: SiDocker },
  'drizzle-orm': { name: 'Drizzle ORM', icon: SiDrizzle },
  electron: { name: 'Electron', icon: SiElectron },
  eslint: { name: 'ESLint', icon: SiEslint },
  fastapi: { name: 'FastAPI', icon: SiFastapi },
  firebase: { name: 'Firebase', icon: SiFirebase },
  flutter: { name: 'Flutter', icon: SiFlutter },
  git: { name: 'Git', icon: SiGit },
  github: { name: 'GitHub', icon: SiGithub },
  'github-actions': { name: 'GitHub Actions', icon: SiGithubactions },
  hono: { name: 'Hono', icon: SiHono },
  html: { name: 'HTML', icon: SiHtml5 },
  hugo: { name: 'Hugo', icon: SiHugo },
  instagram: { name: 'Instagram', icon: SiInstagram },
  javascript: { name: 'JavaScript', icon: SiJavascript },
  jupyter: { name: 'Jupyter', icon: SiJupyter },
  jest: { name: 'Jest', icon: SiJest },
  kotlin: { name: 'Kotlin', icon: SiKotlin },
  lambda: { name: 'AWS Lambda', icon: SiAwslambda },
  mantine: { name: 'Mantine', icon: SiMantine },
  mysql: { name: 'MySQL', icon: SiMysql },
  numpy: { name: 'NumPy', icon: SiNumpy },
  postgresql: { name: 'PostgreSQL', icon: SiPostgresql },
  nestjs: { name: 'Nestjs', icon: SiNestjs },
  nextjs: { name: 'Next.js', icon: SiNextdotjs },
  node: { name: 'Node.js', icon: SiNodedotjs },
  pandas: { name: 'Pandas', icon: SiPandas },
  prisma: { name: 'Prisma', icon: SiPrisma },
  python: { name: 'Python', icon: SiPython },
  python3: { name: 'Python', icon: SiPython },
  prettier: { name: 'Prettier', icon: SiPrettier },
  php: { name: 'PHP', icon: SiPhp },
  raspberrypi: { name: 'Raspberry Pi', icon: SiRaspberrypi },
  react: { name: 'React', icon: SiReact },
  remix: { name: 'Remix', icon: SiRemix },
  rails: { name: 'Ruby on Rails', icon: SiRubyonrails },
  recoil: { name: 'Recoil', icon: SiRecoil },
  rust: { name: 'Rust', icon: SiRust },
  scss: { name: 'SCSS', icon: SiSass },
  'styled-components': { name: 'styled-components', icon: SiStyledcomponents },
  storybook: { name: 'Storybook', icon: SiStorybook },
  svelte: { name: 'Svelte', icon: SiSvelte },
  supabase: { name: 'Supabase', icon: SiSupabase },
  swift: { name: 'Swift', icon: SiSwift },
  tauri: { name: 'Tauri', icon: SiTauri },
  threejs: { name: 'Three.js', icon: SiThreedotjs },
  tensorflow: { name: 'TensorFlow', icon: SiTensorflow },
  typescript: { name: 'TypeScript', icon: SiTypescript },
  trpc: { name: 'tRPC', icon: SiTrpc },
  tailwindcss: { name: 'Tailwind CSS', icon: SiTailwindcss },
  unjs: { name: 'UnJS', icon: SiUnjs },
  vite: { name: 'Vite', icon: SiVite },
  vitest: { name: 'Vitest', icon: SiVitest },
  vue: { name: 'Vue.js', icon: SiVuedotjs },
  x: { name: 'X', icon: SiX },
  tanstack: { name: 'TanStack', icon: TanstackIcon },
} as const;

export const ICON_KEYS = getKeys(ICON_MAP);

export type IconKey = keyof typeof ICON_MAP;

interface Props {
  iconKey: IconKey;
  color?: string;
  className?: string;
  size?: number;
}

export default function Icon({ iconKey, color, ...rest }: Props) {
  if (!ICON_KEYS.includes(iconKey)) return null;

  const SelectedIcon = ICON_MAP[iconKey].icon;
  const SelectedColot = color ?? 'default';

  return <SelectedIcon {...rest} color={SelectedColot} />;
}
