/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PostsIndexRouteImport } from './routes/posts/index'
import { Route as NewIndexRouteImport } from './routes/new/index'
import { Route as SlugIndexRouteImport } from './routes/$slug/index'
import { Route as SlugEditRouteImport } from './routes/$slug/edit'
import { Route as PostsCategoryIndexRouteImport } from './routes/posts/$category/index'
import { Route as PostNewIndexRouteImport } from './routes/post/new/index'
import { Route as PostPostIdIndexRouteImport } from './routes/post/$postId/index'
import { Route as PostPostIdEditRouteImport } from './routes/post/$postId/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsIndexRoute = PostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewIndexRoute = NewIndexRouteImport.update({
  id: '/new/',
  path: '/new/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugIndexRoute = SlugIndexRouteImport.update({
  id: '/$slug/',
  path: '/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugEditRoute = SlugEditRouteImport.update({
  id: '/$slug/edit',
  path: '/$slug/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsCategoryIndexRoute = PostsCategoryIndexRouteImport.update({
  id: '/posts/$category/',
  path: '/posts/$category/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostNewIndexRoute = PostNewIndexRouteImport.update({
  id: '/post/new/',
  path: '/post/new/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostPostIdIndexRoute = PostPostIdIndexRouteImport.update({
  id: '/post/$postId/',
  path: '/post/$postId/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostPostIdEditRoute = PostPostIdEditRouteImport.update({
  id: '/post/$postId/edit',
  path: '/post/$postId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug/edit': typeof SlugEditRoute
  '/$slug/': typeof SlugIndexRoute
  '/new/': typeof NewIndexRoute
  '/posts/': typeof PostsIndexRoute
  '/post/$postId/edit': typeof PostPostIdEditRoute
  '/post/$postId/': typeof PostPostIdIndexRoute
  '/post/new/': typeof PostNewIndexRoute
  '/posts/$category/': typeof PostsCategoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug/edit': typeof SlugEditRoute
  '/$slug': typeof SlugIndexRoute
  '/new': typeof NewIndexRoute
  '/posts': typeof PostsIndexRoute
  '/post/$postId/edit': typeof PostPostIdEditRoute
  '/post/$postId': typeof PostPostIdIndexRoute
  '/post/new': typeof PostNewIndexRoute
  '/posts/$category': typeof PostsCategoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug/edit': typeof SlugEditRoute
  '/$slug/': typeof SlugIndexRoute
  '/new/': typeof NewIndexRoute
  '/posts/': typeof PostsIndexRoute
  '/post/$postId/edit': typeof PostPostIdEditRoute
  '/post/$postId/': typeof PostPostIdIndexRoute
  '/post/new/': typeof PostNewIndexRoute
  '/posts/$category/': typeof PostsCategoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug/edit'
    | '/$slug/'
    | '/new/'
    | '/posts/'
    | '/post/$postId/edit'
    | '/post/$postId/'
    | '/post/new/'
    | '/posts/$category/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug/edit'
    | '/$slug'
    | '/new'
    | '/posts'
    | '/post/$postId/edit'
    | '/post/$postId'
    | '/post/new'
    | '/posts/$category'
  id:
    | '__root__'
    | '/'
    | '/$slug/edit'
    | '/$slug/'
    | '/new/'
    | '/posts/'
    | '/post/$postId/edit'
    | '/post/$postId/'
    | '/post/new/'
    | '/posts/$category/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugEditRoute: typeof SlugEditRoute
  SlugIndexRoute: typeof SlugIndexRoute
  NewIndexRoute: typeof NewIndexRoute
  PostsIndexRoute: typeof PostsIndexRoute
  PostPostIdEditRoute: typeof PostPostIdEditRoute
  PostPostIdIndexRoute: typeof PostPostIdIndexRoute
  PostNewIndexRoute: typeof PostNewIndexRoute
  PostsCategoryIndexRoute: typeof PostsCategoryIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/': {
      id: '/posts/'
      path: '/posts'
      fullPath: '/posts/'
      preLoaderRoute: typeof PostsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new/': {
      id: '/new/'
      path: '/new'
      fullPath: '/new/'
      preLoaderRoute: typeof NewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/': {
      id: '/$slug/'
      path: '/$slug'
      fullPath: '/$slug/'
      preLoaderRoute: typeof SlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/edit': {
      id: '/$slug/edit'
      path: '/$slug/edit'
      fullPath: '/$slug/edit'
      preLoaderRoute: typeof SlugEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$category/': {
      id: '/posts/$category/'
      path: '/posts/$category'
      fullPath: '/posts/$category/'
      preLoaderRoute: typeof PostsCategoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post/new/': {
      id: '/post/new/'
      path: '/post/new'
      fullPath: '/post/new/'
      preLoaderRoute: typeof PostNewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post/$postId/': {
      id: '/post/$postId/'
      path: '/post/$postId'
      fullPath: '/post/$postId/'
      preLoaderRoute: typeof PostPostIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post/$postId/edit': {
      id: '/post/$postId/edit'
      path: '/post/$postId/edit'
      fullPath: '/post/$postId/edit'
      preLoaderRoute: typeof PostPostIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugEditRoute: SlugEditRoute,
  SlugIndexRoute: SlugIndexRoute,
  NewIndexRoute: NewIndexRoute,
  PostsIndexRoute: PostsIndexRoute,
  PostPostIdEditRoute: PostPostIdEditRoute,
  PostPostIdIndexRoute: PostPostIdIndexRoute,
  PostNewIndexRoute: PostNewIndexRoute,
  PostsCategoryIndexRoute: PostsCategoryIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
