/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThemeRouteImport } from './routes/_theme'
import { Route as ThemeIndexRouteImport } from './routes/_theme/index'
import { Route as ThemePostsIndexRouteImport } from './routes/_theme/posts/index'

const ThemeRoute = ThemeRouteImport.update({
  id: '/_theme',
  getParentRoute: () => rootRouteImport,
} as any)
const ThemeIndexRoute = ThemeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ThemeRoute,
} as any)
const ThemePostsIndexRoute = ThemePostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => ThemeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ThemeIndexRoute
  '/posts/': typeof ThemePostsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof ThemeIndexRoute
  '/posts': typeof ThemePostsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_theme': typeof ThemeRouteWithChildren
  '/_theme/': typeof ThemeIndexRoute
  '/_theme/posts/': typeof ThemePostsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/posts/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/posts'
  id: '__root__' | '/_theme' | '/_theme/' | '/_theme/posts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ThemeRoute: typeof ThemeRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_theme': {
      id: '/_theme'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ThemeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_theme/': {
      id: '/_theme/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ThemeIndexRouteImport
      parentRoute: typeof ThemeRoute
    }
    '/_theme/posts/': {
      id: '/_theme/posts/'
      path: '/posts'
      fullPath: '/posts/'
      preLoaderRoute: typeof ThemePostsIndexRouteImport
      parentRoute: typeof ThemeRoute
    }
  }
}

interface ThemeRouteChildren {
  ThemeIndexRoute: typeof ThemeIndexRoute
  ThemePostsIndexRoute: typeof ThemePostsIndexRoute
}

const ThemeRouteChildren: ThemeRouteChildren = {
  ThemeIndexRoute: ThemeIndexRoute,
  ThemePostsIndexRoute: ThemePostsIndexRoute,
}

const ThemeRouteWithChildren = ThemeRoute._addFileChildren(ThemeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ThemeRoute: ThemeRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
