/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PostsIndexRouteImport } from './routes/posts/index'
import { Route as PostNewIndexRouteImport } from './routes/post/new/index'
import { Route as PostPostIdEditRouteImport } from './routes/post/$postId/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsIndexRoute = PostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostNewIndexRoute = PostNewIndexRouteImport.update({
  id: '/post/new/',
  path: '/post/new/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostPostIdEditRoute = PostPostIdEditRouteImport.update({
  id: '/post/$postId/edit',
  path: '/post/$postId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/posts/': typeof PostsIndexRoute
  '/post/$postId/edit': typeof PostPostIdEditRoute
  '/post/new/': typeof PostNewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/posts': typeof PostsIndexRoute
  '/post/$postId/edit': typeof PostPostIdEditRoute
  '/post/new': typeof PostNewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/posts/': typeof PostsIndexRoute
  '/post/$postId/edit': typeof PostPostIdEditRoute
  '/post/new/': typeof PostNewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/posts/' | '/post/$postId/edit' | '/post/new/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/posts' | '/post/$postId/edit' | '/post/new'
  id: '__root__' | '/' | '/posts/' | '/post/$postId/edit' | '/post/new/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PostsIndexRoute: typeof PostsIndexRoute
  PostPostIdEditRoute: typeof PostPostIdEditRoute
  PostNewIndexRoute: typeof PostNewIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/': {
      id: '/posts/'
      path: '/posts'
      fullPath: '/posts/'
      preLoaderRoute: typeof PostsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post/new/': {
      id: '/post/new/'
      path: '/post/new'
      fullPath: '/post/new/'
      preLoaderRoute: typeof PostNewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post/$postId/edit': {
      id: '/post/$postId/edit'
      path: '/post/$postId/edit'
      fullPath: '/post/$postId/edit'
      preLoaderRoute: typeof PostPostIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PostsIndexRoute: PostsIndexRoute,
  PostPostIdEditRoute: PostPostIdEditRoute,
  PostNewIndexRoute: PostNewIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
